### ISSUE TITLE
如果在面试时，告知面试官以前曾因为公司违反劳动法与公司打过官司。有公司会要吗？

### ISSUE THREAD

**Issue by jaune162** [Y1ran/996.Law#81]
RT

如果你是面试官你会怎么办？

**Comment by jaune162** [comment]
理性讨论，文明发言，切勿冲动

**Comment by wxgg** [comment]
属于个人隐私，属于变相口头协定，他敢提前告知，就违反劳动法。但你不说或不承认，不违劳动法。因为这和工作属性没关系。

**Comment by Melody1024** [comment]
你这样想就是奴性太深，打官司是每个公民最基本的人权，法律和司法的本意就是要维护公平正义杨善罚恶，不存在任何道德问题。打官司恰恰说明你自信有正义感，那些不敢招聘“有案在身”的劳动者的企业都是不愿守法，经常违法欺负员工的企业，这样的企业你就应该把他搞到倒闭。

**Comment by jaune162** [comment]
> 你这样想就是奴性太深，打官司是每个公民最基本的人权，法律和司法的本意就是要维护公平正义杨善罚恶，不存在任何道德问题。打官司恰恰说明你自信有正义感，那些不敢招聘“有案在身”的劳动者的企业都是不愿守法，经常违法欺负员工的企业，这样的企业你就应该把他搞到倒闭。

不要太偏激，每个人都有家要养。跟奴性没有关系。如果是只有一少部分公司不会要还好，关键是现在感觉大多数公司应该都不会要。现在的公司有多少是准守劳动法的。

搞倒闭也不是你一句话就能把人家搞倒闭的。

**Comment by Melody1024** [comment]
> > 你这样想就是奴性太深，打官司是每个公民最基本的人权，法律和司法的本意就是要维护公平正义杨善罚恶，不存在任何道德问题。打官司恰恰说明你自信有正义感，那些不敢招聘“有案在身”的劳动者的企业都是不愿守法，经常违法欺负员工的企业，这样的企业你就应该把他搞到倒闭。
> 
> 不要太偏激，每个人都有家要养。跟奴性没有关系。如果是只有一少部分公司不会要还好，关键是现在感觉大多数公司应该都不会要。现在的公司有多少是准守劳动法的。
> 
> 搞倒闭也不是你一句话就能把人家搞倒闭的。

你的说法完全是在扯淡，有家要养就要妥协？你应该多看一篇好的裁判文书找一下自信。

**Comment by jaune162** [comment]
> > > 你这样想就是奴性太深，打官司是每个公民最基本的人权，法律和司法的本意就是要维护公平正义杨善罚恶，不存在任何道德问题。打官司恰恰说明你自信有正义感，那些不敢招聘“有案在身”的劳动者的企业都是不愿守法，经常违法欺负员工的企业，这样的企业你就应该把他搞到倒闭。
> > 
> > 
> > 不要太偏激，每个人都有家要养。跟奴性没有关系。如果是只有一少部分公司不会要还好，关键是现在感觉大多数公司应该都不会要。现在的公司有多少是准守劳动法的。
> > 搞倒闭也不是你一句话就能把人家搞倒闭的。
> 
> 你的说法完全是在扯淡，有家要养就要妥协？你应该多看一篇好的裁判文书找一下自信。

对你很无语，其实就是一个调查贴。却没有一个回答是跟问题有关的。
